name: datetimetest
on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * 1-5"

jobs:
  moragi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Moragi
        run: date
