name: Pull Request
on:
  pull_request:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "poetry"
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
      - name: Install Dependencies
        run: poetry install

      - name: Run test
        run: poetry run invoke test

  static-analysis:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "poetry"
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
      - name: Install Dependencies
        run: poetry install

      - name: Check Code Styles
        run: poetry run invoke check
