name: 일해라 모락이 | 저녁 메뉴 사진
on:
  schedule:
    - cron: "50 8 * * 1-5" # KST 17:50

jobs:
  moragi:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Trigger workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # triggers .github/workflows/work_moragi.yml
        run: gh workflow run work_moragi.yml -f command=send-dinner-menu-summary-with-photo -f confirm_production_send=true
