name: 일해라 모락이
on:
  workflow_dispatch:
    inputs:
      command:
        description: "실행 할 명령 타입. `moragi/cli/commands.py` 에 존재하는 명령어 이름을 입력해주세요."
        required: true
        type: choice
        options:
          - send-daily-meal-summary-with-photo
          - send-next-meal-summary
      target_slack_webhook_url:
        description: "메시지를 보낼 슬랙 웹훅 URL. 없을 경우 secret 에 설정된 프로젝트 기본 값으로 보내집니다."
        required: false
        type: string

jobs:
  moragi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2

      - name: Cache Dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('./poetry.lock') }}

      - name: Install Dependencies if cache doesn't hit
        if: steps.cache.outptus.cache-hit == 'false'
        run: poetry install

      - name: Run Moragi with default Slack Webhook URL
        if: github.event.inputs.target_slack_webhook_url == ''
        run: poetry run python3 -m moragi ${{ github.event.inputs.command }} ${{ vars.CJ_FRESH_MEAL_STORE_ID }} ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Run Moragi with specified Slack Webhook URL
        if: github.event.inputs.target_slack_webhook_url != ''
        run: poetry run python3 -m moragi ${{ github.event.inputs.command }} ${{ vars.CJ_FRESH_MEAL_STORE_ID }} ${{ secrets.SLACK_WEBHOOK_URL }}
