name: 일해라 모락이
on:
  workflow_dispatch:
    inputs:
      command:
        description: "실행 할 명령 타입.\n\n`moragi/cli/commands.py` 에 존재하는 명령어 이름을 입력해주세요."
        required: true
        type: choice
        options:
          - send-daily-menu-summary-with-photo
          - send-next-menu-summary
          - send-today-menu-summary
      target_slack_webhook_url:
        description: "메시지를 보낼 슬랙 웹훅 URL.\n\n없을 경우 secret 에 설정된 프로젝트 기본 값으로 보내집니다."
        required: false
        type: string
      confirm_production_send:
        description: "#냠냠 채널로 메시지 보내기.\n\n체크시 `target_slack_webhook_url` 이 지정되지 않았을때만 메시지가 보내집니다."
        type: boolean

jobs:
  moragi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: poetry
      - name: Install Dependencies
        run: poetry install

      - name: Run Moragi with default Slack Webhook URL
        if: github.event.inputs.target_slack_webhook_url == '' && github.event.inputs.confirm_production_send == 'true'
        run: poetry run python3 -m moragi ${{ github.event.inputs.command }} ${{ vars.CJ_FRESH_MEAL_STORE_ID }} ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Run Moragi with specified Slack Webhook URL
        if: github.event.inputs.target_slack_webhook_url != '' && github.event.inputs.confirm_production_send != 'true'
        run: poetry run python3 -m moragi ${{ github.event.inputs.command }} ${{ vars.CJ_FRESH_MEAL_STORE_ID }} ${{ github.event.inputs.target_slack_webhook_url }}
