name: 일해라 모락이
on:
  workflow_dispatch:
    inputs:
      command:
        description: "실행 할 명령 타입. `moragi/cli/commands.py` 에 존재하는 명령어 이름을 입력해주세요."
        required: true
        type: string

jobs:
  moragi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - uses: snok/install-poetry@v1.3.3
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('./poetry.lock') }}

      - name: Install Dependencies if cache doesn't hit
        if: steps.cache-dependencies.cache-hit != 'true'
        run: poetry install

      - name: Run Moragi
        run: poetry run python3 -m moragi ${{ github.event.inputs.command }} ${{ vars.CJ_FRESH_MEAL_STORE_ID }} ${{ secrets.SLACK_WEBHOOK_URL }}
