name: 일해라 모락이 점심이다 점심
on:
  workflow_dispatch:

jobs:
  moragi:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Trigger workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run work_moragi.yml -f command=send-today-menu-summary -f target_slack_webhook_url=test
